name: GraalVM Native Image builds
on: [push, pull_request]
permissions:
  contents: write
  packages: write
jobs:
  build:
    name: 在 ${{ matrix.os }} 上构建
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: 获取版本号
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: 上传到 release 中 (目前有问题)
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file:  test/uuu*
           tag: ${{ steps.get_version.outputs.VERSION }}
           release_name: 'release_name'
           overwrite: true
           file_glob: true
           body: "这是body"
