name: "测试:上传release"
# 创建新的tag时触发,tag名字就是release的名字
on:
  push:
    tags:
      - 'release*'
permissions:
  contents: write
  packages: write
jobs:
  build:
    name: 在 ${{ matrix.os }} 上构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: 上传到 release 中
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file:  test/a.*
           overwrite: true
           file_glob: true
           body: "这是body"
